[package]
name = "rustMiner"
version = "0.1.0"
authors = ["suba14 <mot.schubert@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
web3 = "0.15.0"
tokio = { version = "1.5.0", features = ["full"] }
